name = "Quartomenter"
uuid = "1c8adf78-70e3-458e-9438-d9689fce1a5f"
authors = ["G. Vituri <56522687+vituri@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
